### ISSUE TITLE
Display pg notices

### ISSUE THREAD

**Issue by i-bash** [i-bash/pg-dev1-web#11]
Egor Rogov:
11. Функции могут выдавать сообщения в процессе работы: RAISE NOTICE 'Hello, world!'; Сложно ли сделать так, чтобы эти сообщения отлавливались и выводились на экран? По идее это тот же самый механизм, что и исключения, но он не вызывает ошибку, а только кладет сообщения в стек.

**Comment by i-bash** [comment]
Через PHP PDO + драйвер PDO_PGSQL это не делается, придётся заменить расширение на pgsql и переписать Pg.php

**Comment by egor-rogov** [comment]
Тогда с низким приоритетом, если будут силы и желание.

**Comment by i-bash** [comment]
Переписал, но pgsql php extension умеет доставать только последний notice.
