### ISSUE TITLE
config.php.example

### ISSUE THREAD

**Issue by egor-rogov** [i-bash/pg-dev1-web#23]
В качестве предложения. Может, сделать config.php.example таким?

```
<?php
const DATA_SOURCE = ['host'=>'localhost','port'=>'5432','dbname'=>'bookstore'];
```

Или даже не example, а прям сразу config.php?

**Comment by i-bash** [comment]
Сделал, но пока example, а то у меня постгрес на сервере, придётся всё время менять config.php
