### ISSUE TITLE
Layout issues

### ISSUE THREAD

**Issue by egor-rogov** [i-bash/pg-dev1-web#25]
Надписи заезжают друг на друга при нешироком окне (Наличие и Заказ):

![screenshot_2017-06-06_12-26-47](https://cloud.githubusercontent.com/assets/12832436/26822783/ee24ce32-4ab3-11e7-88ca-340044646053.png)

Даже при широком они получаются вплотную друг к дружке:

![screenshot_2017-06-06_12-32-06](https://cloud.githubusercontent.com/assets/12832436/26822864/2f247a54-4ab4-11e7-9e28-1fff55233b55.png)

То же самое и в случае, когда есть поле Заказ и кнопка Купить.

**Comment by i-bash** [comment]
В первом приближении решилось заодно с #24. По-хорошему надо делать несколько вариантов разметки под разные размеры экранов, но это трудоёмко.
