### ISSUE TITLE
Error message remains when entering the Shop

### ISSUE THREAD

**Issue by egor-rogov** [i-bash/pg-dev1-web#28]
Создал пользователя buyer с ограниченными правами. Перехожу, например, в Авторы - получаю ожидаемую ошибку:
> permission denied for relation authors_v

Потом перехожу в Магазин и продолжаю видеть то же самое сообщение об ошибке - оно не очистилось. Видимо, из-за того, что при переходе не выполняется никакой новый запрос к базе.

Я вот думаю, может надо при входе в Магазин сразу посылать запрос, как будто нажата кнока Поиск? Это бы все решило.

**Comment by i-bash** [comment]
Если точнее, это потому, что при переходе в магазин не вызывается lib.server, которая чистит сообщения и обращается к бэкенду (server.php), в котором уже выполняется запрос к базе. Добавил очистку при смене подстраницы приложения.
