### ISSUE TITLE
Incorrent error message when no privs for add_book

### ISSUE THREAD

**Issue by egor-rogov** [i-bash/pg-dev1-web#29]
Если у пользователя отобрать права на функцию add_book(), то, при попытке добавить книгу получаем Unexpected server error.
В консоли:
> responseText: "<br /><b>Notice</b>:  Undefined index: authors in <b>/var/www/html/server.php</b> on line <b>40</b><br /><br /><b>Warning</b>:  implode(): Invalid arguments passed in <b>/var/www/html/server.php</b> on line <b>40</b><br />{"data":null,"sql":["select add_book(\n\ttitle=>$1,\n\tauthors=>$2\n) result"],"err":{"code":"42501","message":"permission denied for function add_book"},"notice":null}"

Хорошо бы как-то корректно отработать.

**Comment by egor-rogov** [comment]
Тут вот еще какой момент. У моего пользоваетля нет прав на authors_v. Вкладка Авторы корректно ругается
> permission denied for relation authors_v

Но когда я захожу в Книги, мне нормально показывают список книг; справа видны запросы:
```
select * from catalog_v
---
select * from authors_v
```

По идее обращение к authors_v должно было сломаться, но никакого сообщения об ошибке нет.

Если бы оно сразу выкинуло ошибку, может до добавления книг и дело бы не дошло.

**Comment by egor-rogov** [comment]
Прикладываю дамп для воспроизведения. Пользователь, о котором речь - storekeeper.
[issue29.sql.gz](https://github.com/i-bash/pg-dev1-web/files/1055192/issue29.sql.gz)

**Comment by i-bash** [comment]
Я это уже заметил и пытаюсь побороть. Там проблема в том, что выполняется 2 обращения к серверу, и второе затирает ошибку первого.
