### ISSUE TITLE
"Books" and "Catalog" not working

### ISSUE THREAD

**Issue by egor-rogov** [i-bash/pg-dev1-web#32]
Перестали работать Книги и Каталог. В базу ничего не идет, в веб-консоли жалуется:

> TypeError: lib.clearSql is not a function

**Comment by egor-rogov** [comment]
Что-то там глобально сломалось. Магазин тоже не работает, писок авторов при добавлении книги не подтягивается...

**Comment by egor-rogov** [comment]
Сломалось на вот этом коммите: e3b985b (хотя нет, на 81e2897)
До того все было хорошо.

**Comment by i-bash** [comment]
Как воспроизвести?
Здесь http://pg-dev1.bashtanov.info работает, это мой домашнйи сервер, и все коммиты там есть:

postgres/pg-dev1-web$ git log
commit d3dd81614bc380f105ad9e4cde8311cbfb678282
Author: Ilya Bashtanov <bashtanov@gmail.com>
Date:   Sun Jun 25 15:37:18 2017 +0300

    update jquery to 3.2

commit db2e9edc46f4d573548ec41532df134b9212f52c
Author: Ilya Bashtanov <bashtanov@gmail.com>
Date:   Sun Jun 25 15:36:45 2017 +0300

    #31 sql text is not wrapped

commit 0e5ac2f4cb63e4931e8c55569c9033a8e905aaf0
Author: Ilya Bashtanov <bashtanov@gmail.com>
Date:   Sun Jun 25 15:33:56 2017 +0300

    #2 add column presence checks

.....

**Comment by egor-rogov** [comment]
Забавно. Взгромоздил все на чистую виртуалку - работает. А у меня, видать, от прошлой версии что-то осталось в /var/www/html, что мешало.
Ложная тревога (:
