### ISSUE TITLE
Display operations in accordion on Catalog page

### ISSUE THREAD

**Issue by i-bash** [i-bash/pg-dev1-web#33]
У нас в приложении нигде не
видно таблицу operations, и из-за этого она получается немного
надуманной. Если бы ее содержимое показать в разделе "Каталог", все бы
встало на свои места. Но показывать всю историю операций для всех книг -
это перебор. В идеале хотелось бы иметь возможность "развернуть"
конкретную книгу и увидеть операции только по ней (что-то вроде
"аккордеона").

**Comment by i-bash** [comment]
Сделал черновую версию http://pg-dev1.bashtanov.info
Выглядит пока не идеально, доведу до ума чуть позже.

1. Нравится ли идея в целом?
2. Что показывать в списке операций? Сейчас выводится содержимое всех столбцов таблицы, кроме book_id.
3. Делать ли проверку на существование таблицы operations и выдавать ли специфическое сообщение при её отсутствии?

**Comment by egor-rogov** [comment]
1. В целом ровно то, что нужно!
2. А пусть у нас будет представление operations_v, которое мы предложим написать слушателям. Вот такое, для примера:
```
select book_id,
       case when qty_change > 0 then 'Поступление' else 'Покупка' end op_type, 
       abs(qty_change) qty_change, 
       date_created
from   operations
order by operation_id;
```
Соответственно выводим столбцы "Тип операции", "Изменение кол-ва" и "Дата".

3.  Проверяем существование operations_v, сообщение: Представление для операций будет создано в теме 8 "Взаимодействие клиента с СУБД".
Только хорошо бы сделать так, чтобы все работало и без operations_v, пока не пытаешься раскрыть список операций.

4.  Ккстати, там везде в сообщениях надо бы поправить "Взаимодействие приложения с СУБД" на "Ввзаимодействие клиента к СУБД".)

**Comment by i-bash** [comment]
Переделал на представление, добавил проверку и сообщение. Без operations_v работает, запрос делается каждый раз при раскрытии. Другие сообщения поправил, красоту навёл. Жду критику :).

**Comment by egor-rogov** [comment]
Супер!
Из критики:
1.  Я б горизонтальные черточки убрал, ненужный визуальный шум. (А подсветка строки под курсором --- это хорошо.)
2.  И сдвинул бы все влево, чтобы первый столбец (тип операции) был вровень с названием книги.
3.  А дата нигде не показывается, потому что ее нет?
4.  Еще, мне кажется, надо очищать голубую плашку при запросе к operations_v.

**Comment by i-bash** [comment]
Хм... ответил на e-mail два с лишним часа назад, а комментарий в гитхабе не появляется. Дублирую на веб-странице.

1, 2, 4 - согласен, сделал.
3 - дата везде null, при поступлении и заказе не заполняется, а глубже я не копал.

**Comment by egor-rogov** [comment]
Еще раз проверил, все отлично. Спасибо! Войдет в следующее изменение курса (надо еще саму тему поменять).

**Comment by i-bash** [comment]
Добавил вручную пару дат, отображаются как 2017-08-01. Думаю, пойдёт.
